version: '3'
services:
  database:
    container_name: eksicodeDatabase
    image: mysql:5.7.26
    volumes:
      - ./db/eksicode.sql:/docker-entrypoint-initdb.d/eksicode.sql
    env_file:
      - ./eksicode.env
    environment:
      - MYSQL_ROOT_PASSWORD:$${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:$${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER:$${MYSQL_USER}
      - MYSQL_PASSWORD:$${MYSQL_PASSWORD}
      - TZ=Europe/Istanbul
    networks:
      - eksicode_nw
    healthcheck:
            test: ["CMD","/usr/bin/mysql", "--user:root", "--password:$${MYSQL_ROOT_PASSWORD}", "--execute", "\"SHOW DATABASES;\""]
            interval: 30s
            timeout: 10s
            retries: 5

  backend:
    container_name: eksicodeBackend
    build: ./backend
    volumes:
      - ./backend:/var/www
    env_file:
      - ./eksicode.env
    environment:
      - DB_CONNECTION:$${DB_CONNECTION}
      - DB_HOST:$${DB_HOST}
      - DB_PORT:$${DB_PORT}
      - DB_DATABASE:$${DB_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD:$${MYSQL_ROOT_PASSWORD}
    links:
      - database
    depends_on:
      - database
    restart: on-failure
    networks:
      - eksicode_nw

  phpmyadmin:
    container_name: eksicodePma
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./eksicode.env
    environment:
      MYSQL_USER: $${MYSQL_USER}
      MYSQL_PASSWORD: $${MYSQL_PASSWORD}
      PMA_HOST: $${PMA_HOST}
    ports:
      - "8004:443"
    restart: always
    links:
      - database
    depends_on:
      - database
    networks:
      - eksicode_nw

  web:
    container_name: eksicodeWeb
    image: nginx:alpine
    environment:
      - TZ=Europe/Istanbul
      - PROTOCOL=HTTP
    privileged: true
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/eksicode.crt:/etc/nginx/conf.d/eksicode.crt
      - ./nginx/eksicode.key:/etc/nginx/conf.d/eksicode.key
      - /home/eksicode-frontend/build:/var/www/html
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - eksicode_nw

volumes:
  database:
  backend:
  web:
  phpmyadmin:

networks:
  eksicode_nw:
