version: '3'
services:
  database:
    container_name: eksicodeDatabase
    image: mysql:5.7.26
    volumes:
      - ./db/eksicode.sql:/docker-entrypoint-initdb.d/eksicode.sql
    environment:
      - MYSQL_ROOT_PASSWORD: "]~HBz=8Cgc9U,RR}"
      - MYSQL_DATABASE: "eksicode"
      - MYSQL_USER: "eksicode"
      - MYSQL_PASSWORD: "WBmdjyNgF8P4mKat"
      - TZ=Europe/Istanbul
    networks:
      - eksicode_nw
    healthcheck:
            test: ["CMD","/usr/bin/mysql", "--user=eksicode", "--password=WBmdjyNgF8P4mKat", "--execute", "\"SHOW DATABASES;\""]
            interval: 30s
            timeout: 10s
            retries: 5

  backend:
    container_name: eksicodeBackend
    build: ./backend
    volumes:
      - ./backend:/var/www
    environment:
      - DB_CONNECTION: "mysql"
      - DB_HOST: "database"
      - DB_PORT: 3306
      - DB_DATABASE: "eksicode"
      - DB_USERNAME: "eksicode"
      - DB_PASSWORD: "WBmdjyNgF8P4mKat"
    links:
      - database
    depends_on:
      - database
    restart: on-failure
    networks:
      - eksicode_nw

  phpmyadmin:
    container_name: eksicodePma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_PORT: 3306
      - PMA_HOST: "database"
      - PMA_USER: "eksicode"
      - PMA_PASSWORD: "WBmdjyNgF8P4mKat"
    ports:
      - "8004:80"
    restart: always
    links:
      - database
    depends_on:
      - database
    networks:
      - eksicode_nw

  web:
    container_name: eksicodeWeb
    image: nginx:alpine
    environment:
      - TZ=Europe/Istanbul
      - PROTOCOL=HTTP
    privileged: true
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/eksicode.crt:/etc/nginx/conf.d/eksicode.crt
      - ./nginx/eksicode.key:/etc/nginx/conf.d/eksicode.key
      - /home/eksicode-frontend/build:/var/www/html
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - eksicode_nw

volumes:
  database:
  backend:
  web:
  phpmyadmin:

networks:
  eksicode_nw:
